<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Run on CHROME"
           tests="3"
           failures="1"
           errors="0"
           skipped="2"
           time="31.216">
  <properties />
            <testcase name="Employee_01_Add_New_Employee" time="10.537" classname="com.hrm.employee.Level_16_Live_Coding">
                <failure type="java.lang.AssertionError"
                  message="expected [0357] but found [0278]"
              >
<![CDATA[java.lang.AssertionError: expected [0357] but found [0278]
  org.testng.Assert.fail(Assert.java:99)
  org.testng.Assert.failNotEquals(Assert.java:1037)
  org.testng.Assert.assertEqualsImpl(Assert.java:140)
  org.testng.Assert.assertEquals(Assert.java:122)
  org.testng.Assert.assertEquals(Assert.java:617)
  commons.BaseTest.checkEquals(BaseTest.java:291)
  commons.BaseTest.verifyEquals(BaseTest.java:303)
  com.hrm.employee.Level_16_Live_Coding.Employee_01_Add_New_Employee(Level_16_Live_Coding.java:103)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
  org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
  org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
  org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
  org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
  org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
  java.util.ArrayList.forEach(ArrayList.java:1259)
  org.testng.TestRunner.privateRun(TestRunner.java:794)
  org.testng.TestRunner.run(TestRunner.java:596)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
  org.testng.SuiteRunner.run(SuiteRunner.java:276)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
  org.testng.TestNG.runSuites(TestNG.java:1063)
  org.testng.TestNG.run(TestNG.java:1031)
  com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
  com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
      </failure>

          </testcase>
  
            <testcase name="Employee_01_Add_New_Employee" time="0.0" classname="com.hrm.employee.Level_16_Live_Coding">
          <skipped />
    </testcase>
            <testcase name="Employee_01_Add_New_Employee" time="0.0" classname="com.hrm.employee.Level_16_Live_Coding">
          <skipped />
    </testcase>
  
  
</testsuite>
